call plug#begin('~/.vim/plugged')
Plug 'kien/ctrlp.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

set nocompatible              " be iMproved, required
filetype off                  " required

filetype plugin indent on    " required
highlight Pmenu ctermfg=black ctermbg=white guifg=black guibg=white
highlight Search cterm=NONE ctermfg=white ctermbg=darkgray

set encoding=utf-8
set noswapfile
set cursorline
highlight CursorColumn ctermfg=darkgray ctermbg=lightgray term=bold guifg=black guibg=blue gui=bold cterm=NONE
highlight CursorLine ctermfg=darkgray ctermbg=lightgray term=bold guifg=black guibg=blue gui=bold cterm=NONE
set cursorcolumn
set scrolloff=15
set number
syntax enable
set backspace=eol,start,indent
set whichwrap+=<,>,h,l
set runtimepath^=~/.vim/bundle/ctrlp.vim

filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific plugins

if has('mouse')
  set mouse=a
endif

map <Space> <Leader>

" Ignore case when searching
set ignorecase

" When searching try to be smart about cases 
set smartcase

" Highlight search results
set hlsearch

" Makes search act like search in modern browsers
set incsearch 

" Show matching brackets when text indicator is over them
set showmatch 
" How many tenths of a second to blink when matching brackets
set mat=2

" Use 256 colours (Use this setting only if your terminal supports 256 colours)
set t_Co=256
set background=light

" Set extra options when running in GUI mode
if has("gui_running")
    set guioptions-=T
    set guioptions-=e
    set guitablabel=%M\ %t
endif

set expandtab
set smarttab
set shiftwidth=2
set tabstop=2

set ai
set si
set wrap

map ; :
map j gj
map k gk
map q <S-LEFT>
map w <S-RIGHT>
map t :tabe<ENTER>
map e <END>
map b <HOME>
map gf <c-w>gf

inoremap <C-g> <esc>

" Always show Airline 
set laststatus=2
" let g:airline_powerline_fonts = 1
let g:solarized_termcolors=256
let g:airline_theme = 'term_light'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'


function! HasPaste()
  if &paste
     return 'PASTE MODE  '
  endif
     return ''
endfunction
